### ISSUE TITLE
Unexpected HTTP response 403 for Hugo 0.70.0

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-hugo#310]
## Describe the bug

This was a temporary problem. But this action failed to catch the error.

<details>
<summary>Click to expand the log</summary>

https://github.com/peaceiris/peaceiris.com/runs/654642892?check_suite_focus=true#step:4:6

```
(node:2941) UnhandledPromiseRejectionWarning: Error: Unexpected HTTP response: 403
    at /home/runner/work/_actions/peaceiris/actions-hugo/v2/lib/index.js:3498:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/peaceiris/actions-hugo/v2/lib/index.js:3413:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

## Your YAML file

- A link to your repository
- A link to your YAML file

## Additional context

Related:
- https://github.com/gohugoio/hugo/issues/7259

**Comment by peaceiris** [comment]
Closed by #363
